[package]
name = "playlog"
version = "0.1.0"
authors = ["kurt spindler <kespindler@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
chrono = { version = "0.4", features = ["serde"] }
nix = "0.11.0"
indexmap = "1.0.1"
log = "0.4.3"
lazy_static = "1.0"


